### ISSUE TITLE
[Task] tokenFunction 구현

### ISSUE THREAD

**Issue by YeChan8812** [codestates/Cutcard#28]
### ISSUE
- Group: server
- Type: feature
- Detail: token 생성과 인증에 필요한 함수 생성

### TODO
 1. [x] token 생성 함수
 2. [x] token 인증 함수
 3. [x] token 응답 함수

### Estimated time
> Pick one

`3h`
