### ISSUE TITLE
[Task] 공통 컴포넌트 구현

### ISSUE THREAD

**Issue by Ohney** [codestates/Cutcard#4]
### ISSUE
- Group: client
- Type: feature
- Detail: 공통 컴포넌트 구현

### TODO
 1. [x] Base Client (push, 로고 구현)
 2. [x] 로그인/회원가입 구현
 3. [x] 로그인 성공시 회원 이름 구현
 4. [x] 네비바
 5. [x] 버튼 (회원가입 ..)
 6. [x] Footer

### Estimated time
`6h`

각 항목 당 `1h`
